<?php

namespace AppBundle\Repository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends TranslatableRepository
{
	function __construct($entityManager)
	{
		parent::__construct($entityManager, $entityManager->getClassMetadata('AppBundle\Entity\Collection'));
	}

	function getCollection($userId)
	{
		$qb = $this->createQueryBuilder('col')
			->select('col, sl, c')
			->join('col.user', 'u')
			->leftJoin('col.slots', 'sl')
			->leftJoin('sl.card', 'c')
			->andWhere('u.id = ?1')
			->setParameter(1, $userId);

		return $this->getOneOrNullResult($qb);
	}
}
