<?php

namespace AppBundle\Repository;

/**
 * StarterPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarterPackRepository extends TranslatableRepository
{
	function __construct($entityManager)
	{
		parent::__construct($entityManager, $entityManager->getClassMetadata('AppBundle\Entity\StarterPack'));
	}

	function findAll()
	{
		$qb = $this->createQueryBuilder('sp')
			->select('sp, s, sps, c')
			->join('sp.set', 's')
			->leftJoin('sp.slots', 'sps')
			->leftJoin('sps.card', 'c')
			->orderBy('s.position', 'ASC')
			->addOrderBy('sp.code', 'ASC')
			->addOrderBy('c.code', 'ASC');

		return $this->getResult($qb);
	}
}
